name: Automatically Deployment // workflow를 실행시키기 위한 event 명

on: [main] // workflow를 실행시킬 브런치와 요청(push, pull request)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: |
          echo "VITE_API_KEY=${{ secrets.VITE_API_KEY }}" >> .env
          npm run build

      - name: Deploy
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist
