name: Automatically Deployment

on: [push]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Setting .env
        run: |
          echo "VITE_API_KEY=${{ secrets.VITE_API_KEY }}" >> .env
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
